### ISSUE TITLE
Aula 14 - ex 1

### ISSUE THREAD

**Issue by eribeiro2009** [eribeiro2009/TreinamentoSQL#16]
listar quanto cada vendedor vendeu mês a mês em 2011. Mostrar na mesma query o valor da comisão considerando 10% de comissão sobre o valor do pedido. Listar o nome do vendor na mesma consulta

**Comment by brokenghosssst** [comment]
SELECT   p.BusinessEntityID as cod_empregado
		,pp.FirstName as nome_empregado
		,pp.LastName as sobrenome_empregado
		,year(h.ShipDate) as ano
		,month(h.ShipDate) as mes
		,sum(h.TotalDue) as vendas_produtos
		,sum(h.TotalDue) *0.10 as comissao_vendedor
FROM Sales.SalesOrderHeader as h
INNER JOIN Sales.SalesPerson as p
ON h.SalesPersonID = p.BusinessEntityID
INNER JOIN Person.Person as pp
ON pp.BusinessEntityID = p.BusinessEntityID
WHERE year(h.ShipDate) = '2011'
GROUP BY  p.BusinessEntityID
		 ,pp.FirstName
		 ,pp.LastName
		 ,year(h.ShipDate) 
		 ,month(h.ShipDate) 
;
