### ISSUE TITLE
Aula 14 - ex 2

### ISSUE THREAD

**Issue by eribeiro2009** [eribeiro2009/TreinamentoSQL#17]
listar quanto cada cliente comprou mês a mês em 2011. Mostrar na mesma a quantidade de pedidos. Listar o nome do cliente na mesma consulta

**Comment by brokenghosssst** [comment]
SELECT	 c.CustomerID as cod_cliente
		,p.FirstName as nome
		,year(h.OrderDate) as ano_pedido
		,month(h.OrderDate) as mes_pedido
		,sum(h.TotalDue) as total_pedido
FROM Sales.SalesOrderHeader as h
INNER JOIN Sales.Customer as c
ON h.CustomerID = c.CustomerID
INNER JOIN Person.Person as p
ON p.BusinessEntityID = c.PersonID
WHERE year(h.OrderDate) = '2011'
GROUP BY c.CustomerID 
		,p.FirstName 
		,year(h.OrderDate) 
		,month(h.OrderDate)
;
