### ISSUE TITLE
Aula 14 - exe 3

### ISSUE THREAD

**Issue by eribeiro2009** [eribeiro2009/TreinamentoSQL#18]
Listar a quantidade de pedidos de compra (Purchasing.PurchaseOrderHeader) por status, total dos pedidos. Somente Pedidos do ano 2011 e status com mais de 100 pedidos

**Comment by brokenghosssst** [comment]
SELECT   h.Status 
		,case 
			when h.Status = 1 then 'Ativo'
			when h.Status = 3 then 'Cancelado'
			when h.Status = 4 then 'Suspenso'
		 end as descricao_status
		,year(h.OrderDate) as ano
		,sum(h.TotalDue) as total_pedidos
		,count(*) as qntd
FROM Purchasing.PurchaseOrderHeader as h
WHERE year(h.OrderDate) = '2011'
GROUP BY h.Status 
		,year(h.OrderDate) 
;
