### ISSUE TITLE
Aula 14 - exe 4

### ISSUE THREAD

**Issue by eribeiro2009** [eribeiro2009/TreinamentoSQL#19]
Listar o numero do pedido de compra, código do empregado, nome do empregado, vendorID e nome do vendor, pedidos entre os valores 200 e 5000, ano 2011 e messe entre Abril e Novembro

**Comment by brokenghosssst** [comment]
SELECT	 h.PurchaseOrderID as cod_pedido
		,h.EmployeeID as cod_empregado
		,p.FirstName as nome
		,p.LastName as sobrenome
		,p.BusinessEntityID as cod_vendedor
		,h.TotalDue as total_pedido
		,year(h.OrderDate) as ano
		,month(h.OrderDate) as mes
FROM Purchasing.PurchaseOrderHeader as h
INNER JOIN Person.Person as p
ON p.BusinessEntityID = h.EmployeeID
WHERE year(h.OrderDate) = '2011'
AND month(h.OrderDate) BETWEEN 4 AND 11
AND h.TotalDue BETWEEN 200 AND 5000
;
